### ISSUE TITLE
Capture Team history

### ISSUE THREAD

**Issue by streichsbaer** [DinisCruz/Maturity-Models#105]
As a stakeholder, I want to see the maturity evolution that a specific team has made over a certain timeframe so that I can shower them with compliments and prizes. 

When saving the maturity score of a team, the file could contain a timestamp e.g. team-A-XXXXXX.json that allows me to re-create saves over a certain period.

Saving the timestamp could be optional and used similarly to a tag (e.g July 2016).

**Comment by DinisCruz** [comment]
That is already on the pipeline and my current plan is to implement it with git commits (see #93) 
that will give your a full historic analysis of the data (and proper backups with integrity and chain of authority)
