### ISSUE TITLE
Fix scrutinizer build bug (submodule related)

### ISSUE THREAD

**Issue by DinisCruz-Dev** [DinisCruz/Maturity-Models#14]
After adding support for it (see #13) the build is failing because the submodules are not being cloned:

![image](https://cloud.githubusercontent.com/assets/5729981/15651300/977f93a8-2676-11e6-9e2f-66bf372cd12b.png)

The solution is to do something like:

![image](https://cloud.githubusercontent.com/assets/5729981/15651322/b47c72fa-2676-11e6-81cd-54a80ae37f8c.png)

**Comment by DinisCruz** [comment]
closing since scrutinizer is not used
