### ISSUE TITLE
There is no Authentication and Authorization

### ISSUE THREAD

**Issue by DinisCruz** [DinisCruz/Maturity-Models#16]
all data is exposed to everybody

**Comment by DinisCruz** [comment]
Risk accepted due to the fact that there is no sensitive or confidential data hosted in the live sites

**Comment by streichsbaer** [comment]
There is free for open-source authentication library called [auth0](https://auth0.com) that we could explore for this purpose.

Node SDK:
- https://github.com/auth0/node-auth0
