### ISSUE TITLE
Bug when creating new teams from clean install

### ISSUE THREAD

**Issue by DinisCruz** [DinisCruz/Maturity-Models#172]
I believe this is the issue that Christian Martorella reported 

![image](https://cloud.githubusercontent.com/assets/656739/19638946/1420dfd2-99ce-11e6-9d09-5721f4a65dc7.png)

**Comment by laramies** [comment]
Yes, that is correct.  But now I am experiencing a different error:
1) When I click New team, a new team with a Random name is created (Team-xlsd)
2) In the team page, there is an input (Team Name:)  that seems to be supposed to allow you to change the name with a save button. If I  introduce a new name and click save, nothing happens. I get a "File saved ok" in a green tag, but the team name stays the same (Team-xlsd)

Any idea where is the error?

**Comment by DinisCruz** [comment]
Yeah, I think I had the same error yesterday. Let me take a look at it

**Comment by DinisCruz** [comment]
Btw a way to go around this is to edit the files directly on the data folder (which allows you to name them better). 

The API already supports renaming (need to wire that in the UI)

**Comment by DinisCruz** [comment]
@laramies can you try now?

It's not perfect but it should at least create the new team using the UI

here it is working in action on the QA server (http://138.68.145.52)

1) on the projects page http://138.68.145.52/view/project/bsimm
![image](https://cloud.githubusercontent.com/assets/656739/19938798/32de3134-a11e-11e6-9551-7edace42ca6a.png)

2) click on the 'new team' link, which should lead to this page:

![image](https://cloud.githubusercontent.com/assets/656739/19938854/5b84b6f8-a11e-11e6-959c-b1e2370741fb.png)

3) go to edit tab

![image](https://cloud.githubusercontent.com/assets/656739/19938873/6ac2261e-a11e-11e6-9f71-6fff958f8f35.png)

4) change the title

![image](https://cloud.githubusercontent.com/assets/656739/19938885/7cf1bec6-a11e-11e6-80d7-92ad0f8d0929.png)

5) open the raw tab to confirm it was changed 

![image](https://cloud.githubusercontent.com/assets/656739/19938893/860f1cb0-a11e-11e6-8a65-2843918eb05f.png)

6) change a couple mappings

![image](https://cloud.githubusercontent.com/assets/656739/19938901/93a9e5da-a11e-11e6-8cdf-c7db08c2e915.png)

7) confirm they were saved

![image](https://cloud.githubusercontent.com/assets/656739/19938912/9c53a4d2-a11e-11e6-94a8-b15d51a10cb7.png)

8) confirm they shown up in the 'table view'

![image](https://cloud.githubusercontent.com/assets/656739/19938925/ab1e34d2-a11e-11e6-9267-0f1d418539e6.png)

9) and on the 'radar' view

![image](https://cloud.githubusercontent.com/assets/656739/19939506/3ff7f8fc-a121-11e6-9f47-d2738db2469f.png)

**Comment by DinisCruz** [comment]
latest version as just deployed to http://138.68.145.52/ doesn't show this issue any more 

@laramies can you try again?
