### ISSUE TITLE
issue running submodule update

### ISSUE THREAD

**Issue by JamesWharton** [DinisCruz/Maturity-Models#178]
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:OWASP/Maturity-Models-API.git' into submodule path 'C:/Users/James/Github/Downloads/Maturity-model/Maturity-Models/code/api' failed
Failed to clone 'code/api'. Retry scheduled

**Comment by JamesWharton** [comment]
actually this is more of an issue connecting SSH in general as opposed to "submodule update"

**Comment by DinisCruz** [comment]
did it work? (after setting up your ssh keys?)

**Comment by JamesWharton** [comment]
Yes fixed this morning - machine needed a restart also after keys were setup.

**Comment by DinisCruz** [comment]
great :)
