### ISSUE TITLE
readme cd ui?

### ISSUE THREAD

**Issue by JamesWharton** [DinisCruz/Maturity-Models#179]
so I have 2 ui folders one under /code and one under .git/modules/code . Which one do I run the npm --quiet in ?

**Comment by DinisCruz** [comment]
well spotted, those instructions were out of date (the ui folder was refactored into the code folder)

In this case you run it from the the `/code` one which is the real one, the `.git/modules/code` is an internal git folder which is related to the clone created by the submodule

btw, can you try `npm run dev` instead of `npm start` (this will also monitor the file system and re-deploy on code changes

I've updated the Readme.md file

**Comment by JamesWharton** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle maturity-models@0.0.1~predev: maturity-models@0.0.1
6 silly lifecycle maturity-models@0.0.1~predev: no script for predev, continuing
7 info lifecycle maturity-models@0.0.1~dev: maturity-models@0.0.1
8 verbose lifecycle maturity-models@0.0.1~dev: unsafe-perm in lifecycle true
9 verbose lifecycle maturity-models@0.0.1~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\users\james\Github\downloads\Maturity Models\Maturity-Models\node_modules.bin;C:\Users\James\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\James\bin;C:\Program Files\Broadcom\Broadcom 802.11;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Hewlett-Packard\SimplePass;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone;C:\Windows\system32\config\systemprofile.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\James\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle maturity-models@0.0.1~dev: CWD: C:\users\james\Github\downloads\Maturity Models\Maturity-Models
11 silly lifecycle maturity-models@0.0.1~dev: Args: [ '/d /s /c', 'cd code/ui; gulp watch' ]
12 silly lifecycle maturity-models@0.0.1~dev: Returned: code: 1  signal: null
13 info lifecycle maturity-models@0.0.1~dev: Failed to exec dev script
14 verbose stack Error: maturity-models@0.0.1 dev: `cd code/ui; gulp watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid maturity-models@0.0.1
16 verbose cwd C:\users\james\Github\downloads\Maturity Models\Maturity-Models
17 error Windows_NT 6.3.9600
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "dev"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error maturity-models@0.0.1 dev: `cd code/ui; gulp watch`
22 error Exit status 1
23 error Failed at the maturity-models@0.0.1 dev script 'cd code/ui; gulp watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the maturity-models package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cd code/ui; gulp watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs maturity-models
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls maturity-models
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by DinisCruz** [comment]
hum, do you have gulp installed?

**Comment by JamesWharton** [comment]
$ gulp -v
[22:40:59] CLI version 3.9.1

**Comment by DinisCruz** [comment]
humm what is the command that you used to get that?

Can you create a video (or small animated git) with how you are running it?

**Comment by DinisCruz** [comment]
have you tried the docker images?

( either building it or getting it from Docker hub)

**Comment by DinisCruz** [comment]
btw, where you able to get this running?
For reference see the full build and test execution at https://travis-ci.org/OWASP/Maturity-Models/builds/177179360

**Comment by JamesWharton** [comment]
Hey Dinis - sorry man missed your email, I am about 3rd of the way through
an intensive nodejs course which is really cool and at the same time really
demanding as there is so much i want to do but so much basic stuff i need
to learn first. I have a project to develop a platform /app for a property
company which i want to develop in node, i have had a play around with jwt
and authentication to.

I also want to understand the sdlc and then where all the security stuff
fits, threat modelling etc in but there never seems to be enough time to do
everything :) Let me know when you have some time as would be great to pick
your brains to understand some more about it. I need to read your book
again also - hows that going ?

I have done about half the juice-shop stuff using burp but it would be cool
to try some other products also.

Thanks for the invite for weekend also, unfortunately I  am already
committed to an in-laws function but thanks for thinking of me.

Hope your good.

James

**Comment by DinisCruz** [comment]
no probs, closing this issue since the code has moved on quite a bit since you tried.

and yeah, let's catch up for lunch or dinner (ping me an email)
