### ISSUE TITLE
Extend team raw view to show activities mappings

### ISSUE THREAD

**Issue by DinisCruz** [DinisCruz/Maturity-Models#202]
This should help with #185 (make it easier to integrate with confluence)

**Comment by DinisCruz** [comment]
done 

![image](https://cloud.githubusercontent.com/assets/656739/21193427/357ab2b0-c224-11e6-8a9b-b623aa8bb9b6.png)

now let's see what it looks like in confluence

**Comment by DinisCruz** [comment]
I made a couple ui changes to make it easier to read (split by level, added an horizontal line and moved the answers to the left)

On that last change, which one is easier to read?

A) with answers on the left

![image](https://cloud.githubusercontent.com/assets/656739/21220214/c949624e-c2af-11e6-8fd5-7b6193d2509a.png)

B) with answers on the right

![image](https://cloud.githubusercontent.com/assets/656739/21220224/d408be14-c2af-11e6-8cb3-0ab0d8c941f8.png)


I think B) looks visually better, but A) is easier to read (i.e. find the answer to a particular question)

**Comment by swierckx** [comment]
I find B easier to read since it follow the structure of a conversation where the answer follows the question. This might be a cultural preference though.

B is indeed visually better.

I would opt for B

**Comment by DinisCruz** [comment]
ok, it looks like B) is the consensus :) 

![image](https://cloud.githubusercontent.com/assets/656739/21222100/28ee4950-c2b8-11e6-95db-ba68b44ee604.png)

thx @swierckx

I do like B to since it feels more balanced

So B) will be
