### ISSUE TITLE
Add OpenSAMM project and test data

### ISSUE THREAD

**Issue by DinisCruz** [DinisCruz/Maturity-Models#74]
This would help with the current project separation and allow the MaturityModels to be used by the OWASP Open SAMM community

Assigned to @streichsbaer

**Comment by streichsbaer** [comment]
Done and currently sitting in my public repo. Will transfer to OWASP repo once I get permissions.

**Comment by DinisCruz** [comment]
yap and I have add it as a submodule

**Comment by DinisCruz** [comment]
I was talking with Tony at AppSecEU about making this an OWASP project (#84), my only worry is creating too many repos in that organization (or we can create a new [MaturityModels](https://github.com/MaturityModels) organization)
